### ISSUE TITLE
前端页面失焦(移出)后再移入会触发接口重复请求

### ISSUE THREAD

**Issue by lbsu** [eosphoros-ai/DB-GPT-Web#3]
操作/场景：使用 db-gpt dashboard 功能，发送信息后先切换到浏览器其他 tab 页再切回来。
预期表现：页面等待接口数据返回并展示数据
实际表现：页面 cancel 了原请求并重新发了一个请求，造成后端重复处理。

**Comment by yhjun1026** [comment]
这个问题 和流式输出的组件使用有关系在想法办法解决中

**Comment by Gj-12222** [comment]
> 

还没解决吗？

**Comment by 2976151305** [comment]
已重构聊天组件，修复了该问题
