### ISSUE TITLE
[feature]新增prompts页面的“场景”、“次级场景”栏能提供下拉菜单让用户选择

### ISSUE THREAD

**Issue by zhouzj1610** [eosphoros-ai/DB-GPT-Web#55]
![image](https://github.com/eosphoros-ai/DB-GPT-Web/assets/137265386/df2b6c1b-6fa1-496d-9702-ae1cb9393c7d)
希望能根据系统现有场景，提供一些内置选项，让用户直接选择，多谢。

**Comment by Aralhi** [comment]
done #58
