### ISSUE TITLE
[feature]可以添加对GLM-4的支持吗

### ISSUE THREAD

**Issue by Halflifefa** [eosphoros-ai/DB-GPT-Web#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
智谱ai近期发布了GLM-4模型，性能媲美GPT-4，请问有添加对这个模型的支持的意向吗

**Describe alternatives you've considered**

**Additional context**

**Comment by csunny** [comment]
Already supported.

**Comment by csunny** [comment]
Create model and choose `zhipu_proxyllm`,  `proxyllm_backend` parameter need to set to `glm-4`.
![image](https://github.com/eosphoros-ai/DB-GPT-Web/assets/17919400/0be80530-9d51-4062-a526-24bc384c9697)
